[theme]
primaryColor = "#FFB81C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F4F8"
textColor = "#003087"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
